=== raml-apis/Salesforce/schemas/describe.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fields" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "length" : {
              "type" : "number" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "defaultValue" : {
              "type" : "object" ,
              "required" : false
            } ,
            "updateable" : {
              "type" : "boolean" ,
              "required" : false
            } ,
            "label" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      
    } ,
    "updateable" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "label" : {
      "type" : "string" ,
      "required" : false
    } ,
    "keyPrefix" : {
      "type" : "string" ,
      "required" : false
    } ,
    "custom" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "urls" : {
      "type" : "object" ,
      "required" : false
    } ,
    "childRelationships" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "field" : {
              "type" : "string" ,
              "required" : false
            } ,
            "deprecatedAndHidden" : {
              "type" : "boolean" ,
              "required" : false
            }
          }
        }
      
    } ,
    "createable" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "customSetting" : {
      "type" : "boolean" ,
      "required" : false
    }
  }
}

=== raml-apis/Salesforce/examples/describe-example.json
{
  "name" : "Account" ,
  "fields" : [
    {
      "length" : 18 ,
      "name" : "Id" ,
      "type" : "id" ,
      "defaultValue" : {
        "value" : null
      } ,
      "updateable" : false ,
      "label" : "Account ID" 
    } 
  ] ,
  "updateable" : true ,
  "label" : "Account" ,
  "keyPrefix" : "001" ,
  "custom" : false ,
  "urls" : {
    "uiEditTemplate" : "https://na1.salesforce.com/{ID}/e" ,
    "sobject" : "/services/data/v20.0/sobjects/Account" ,
    "uiDetailTemplate" : "https://na1.salesforce.com/{ID}" 
  } ,
  "childRelationships" : [
    {
      "field" : "ParentId" ,
      "deprecatedAndHidden" : false 
    } 
  ] ,
  "createable" : true ,
  "customSetting" : false 
}
