=== raml-apis/Salesforce/schemas/limits.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "DailyApiRequests" : {
      "type" : "object" ,
      "required" : false
    } ,
    "DailyAsyncApexExecutions" : {
      "type" : "object" ,
      "required" : false
    } ,
    "DailyBulkApiRequests" : {
      "type" : "object" ,
      "required" : false
    } ,
    "DailyStreamingApiEvents" : {
      "type" : "object" ,
      "required" : false
    } ,
    "StreamingApiConcurrentClients" : {
      "type" : "object" ,
      "required" : false
    }
  }
}

=== raml-apis/Salesforce/examples/limits-example.json
{
  "DailyApiRequests" : {
    "Remaining" : "4980" ,
    "Max" : "5000"
  } ,
  "DailyAsyncApexExecutions" : {
    "Remaining" : "250000" ,
    "Max" : "250000"
  } ,
  "DailyBulkApiRequests" : {
    "Remaining" : "3000" ,
    "Max" : "3000"
  } ,
  "DailyStreamingApiEvents" : {
    "Remaining" : "1000" ,
    "Max" : "1000"
  } ,
  "StreamingApiConcurrentClients" : {
    "Remaining" : "10" ,
    "Max" : "10"
  }
}
