=== raml-apis/Salesforce/schemas/version.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "sobjects" : {
      "type" : "string" ,
      "required" : false
    } ,
    "licensing" : {
      "type" : "string" ,
      "required" : false
    } ,
    "connect" : {
      "type" : "string" ,
      "required" : false
    } ,
    "search" : {
      "type" : "string" ,
      "required" : false
    } ,
    "query" : {
      "type" : "string" ,
      "required" : false
    } ,
    "tooling" : {
      "type" : "string" ,
      "required" : false
    } ,
    "chatter" : {
      "type" : "string" ,
      "required" : false
    } ,
    "recent" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Salesforce/examples/version-example.json
{
  "sobjects" : "/services/data/v26.0/sobjects" ,
  "licensing" : "/services/data/v26.0/licensing" ,
  "connect" : "/services/data/v26.0/connect" ,
  "search" : "/services/data/v26.0/search" ,
  "query" : "/services/data/v26.0/query" ,
  "tooling" : "/services/data/v26.0/tooling" ,
  "chatter" : "/services/data/v26.0/chatter" ,
  "recent" : "/services/data/v26.0/recent"
}
